version: '3.8'
services:
  astra-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OLLAMA_HOST=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/app/src