
use_default_settings: true

search:
  formats:
    - json
  safe_search: 0

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "f8e9a1b2c3d4e5f6_astra_fin_sovereign_key_999" 
  limiter: false
  image_proxy: false